version: "3.8"

services:
  gateway-service:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  chatmessenger-service:
    build:
      context: ./MessageService
      dockerfile: Dockerfile
#    ports:
#      - "8001:8095"
  chatmessenger-database:
    image: mysql:8.2.0-oracle
    command: 
    volumes: 
      - ./MessageService/db/data:/var/lib/mysql:delegated
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 3
    env_file:
      - ./MessageService/db/.env
  character-service:
    build:
      context: ./CharacterService
      dockerfile: Dockerfile
  character-database:
    image: mongo:7.0.3
    command: 
    volumes: 
      - ./CharacterService/db/data:/data/db:delegated
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    env_file:
      - ./CharacterService/db/.env
  avatar-service:
    build:
      context: ./AvatarService
      dockerfile: Dockerfile
#    ports:
#      - "8003:80"
  bookmark-service:
    build:
      context: ./BookmarkService
      dockerfile: Dockerfile
#    ports:
#      - "8004:80"
  profile-service:
    build:
      context: ./ProfileService
      dockerfile: Dockerfile
#    ports:
#      - "8005:80"
  report-service:
    build:
      context: ./ReportService
      dockerfile: Dockerfile
#    ports:
#      - "8006:80"
      #TODO Set things like the locations as environment vars
    #env_file:
    #  - ./question/.env
