name: Avatar Service .NET Test

on:
  push:
    branches: [ "dev" ]
    paths:
    - 'AvatarService/**' 
  pull_request:
    branches: [ "dev", "main" ]
    paths:
    - 'AvatarService/**' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./AvatarService
      run: dotnet restore
    - name: Build
      working-directory: ./AvatarService
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./AvatarService
      run: dotnet test --no-build --verbosity normal
