name: Chat Service Docker Push

on:
  push:
    tags:        
      - '*'  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/chatbox-messageservice --tag ${{ secrets.DOCKERHUB_USERNAME }}/chatbox-messageservice:$(date +%s)
