name: Report Service Docker Push

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - uses: actions/checkout@v3
      - name: Log in to Docker
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      #    - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: ./ReportService
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/chatbox-reportservice --tag ${{ secrets.DOCKERHUB_USERNAME }}/chatbox-reportservice:${{ env.RELEASE_VERSION }}

      #    - uses: actions/checkout@v3
      - name: Push latest tag
        working-directory: ./ReportService
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chatbox-reportservice:latest

      #    - uses: actions/checkout@v3
      - name: Push archival tag
        working-directory: ./ReportService
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chatbox-reportservice:${{ env.RELEASE_VERSION }}
